### ISSUE TITLE
Include instructions on how to create test Opus packet files for example

### ISSUE THREAD

**Issue by sblandford** [samirkumardas/opus-to-pcm#16]
ffmpeg and opusenc produce output with OGG encapsulation. There doesn't seem to be any way around this.

I would like to test with my own Opus encoded audio data. Some docs on how to create the *.txt packet files would be useful.

**Comment by samirkumardas** [comment]
It won't be easy. I took the raw opus data from the application I worked with.
You can look at opusencoder documentation to convert wav/pcm data to opus 
http://opus-codec.org/docs/
