### ISSUE TITLE
Make this work on node without browser support

### ISSUE THREAD

**Issue by shyamsfo** [samirkumardas/opus-to-pcm#17]
Is it possible to have this module work as a pure node module, taking in an opus stream and producing pcm stream without using the browser?

**Comment by samirkumardas** [comment]
You can use Emscripten version of [libopus](https://opus-codec.org/) instead. You don't need this library anymore.

You will find several projects on github regarding Emscripten version.  I have also a project https://github.com/samirkumardas/another-libopus.js 
you can find instruction on how to build from source as well.

**Comment by shyamsfo** [comment]
Thanks. Will try !!
