### ISSUE TITLE
How to convert to PCM 16 bit?

### ISSUE THREAD

**Issue by farooqkz** [samirkumardas/opus-to-pcm#19]
How can I do that? Should I change something in the source code?

**Comment by samirkumardas** [comment]
Not possible explicitly as` [decodeAudioData](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/decodeAudioData)` does not have such provision.  You can get 16 Bit depending on the platform you are using.
If you need 16 bit PCM strictly, you can use [libopus](https://github.com/samirkumardas/another-libopus.js)
